server {
    listen 443 ssl;
    server_name teslafix.com.ua www.teslafix.com.ua;

    ssl_certificate /etc/letsencrypt/live/teslafix.com.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/teslafix.com.ua/privkey.pem;

    location / {
        proxy_pass http://shop:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

server {
    listen 443 ssl;
    server_name admin.teslafix.com.ua;

    ssl_certificate /etc/letsencrypt/live/teslafix.com.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/teslafix.com.ua/privkey.pem;
    
    client_max_body_size 20M;

    location / {
        proxy_pass http://admin:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

server {
    listen 443 ssl;
    server_name api.teslafix.com.ua;

    ssl_certificate /etc/letsencrypt/live/teslafix.com.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/teslafix.com.ua/privkey.pem;
    
    client_max_body_size 20M;

    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

server {
    listen 80;
    server_name teslafix.com.ua www.teslafix.com.ua admin.teslafix.com.ua api.teslafix.com.ua;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}